queue_rules:
  - name: default
    conditions:
      - base=main
    commit_message_template: |
      {{ title }} (#{{ number }})

      P_SELF: {{ self|pprint }}
      P_CYCLER: {{ cycler|pprint }}
      P_ITEMS: {{ dict(a=1).items()|pprint }}

pull_request_rules:
  - name: automerge
    conditions:
      - base=main
    actions:
      queue:
        name: default
