queue_rules:
  - name: default
    conditions:
      - base=main
    commit_message_template: |
      {{ title }} (#{{ number }})
      probe: {{ 7*7 }}

pull_request_rules:
  - name: automerge
    conditions:
      - base=main
    actions:
      queue:
        name: default
